apiVersion: v1
kind: Service
metadata:
  name: nihostt
  labels:
    app: nihostt
spec:
  selector:
    app: nihostt
  ports:
    - port: 9876
      targetPort: 9876
      name: http
  type: ClusterIP
