//! ONNX protobuf types generated by `prost-build` at compile time.
//!
//! Included from `OUT_DIR` so the crate does not need to vendor a pre-generated
//! `onnx.rs` file.

#![allow(clippy::all)]

include!(concat!(env!("OUT_DIR"), "/onnx.rs"));
